### ISSUE TITLE
[Bug]:  [Low Priority] Cannot run tests from a test's local folder. `conftest` is not found.

### ISSUE THREAD

**Issue by afourney** [microsoft/autogen#1120]
### Describe the bug

Prior to #1110, it was possible to run the tests from a test's local directory. E.g.

```sh
cd autogen/test/agentchat/contrib
python test_compressible_agent.py
```
or 
```sh
cd autogen/test/agentchat/contrib
pytest test_compressible_agent.py
```

But now, doing so raises the error: 
```
ModuleNotFoundError: No module named 'conftest'
```

Now, tests need to be run from the test root folder:
```sh
cd autogen/test
pytest agentchat/contrib/test_compressible_agent.py
```

This isn't a real problem, but it is a change in prior behavior, and it took me a minute to understand what was going on despite considerable prior experience with the tests.

**Comment by rickyloynd-microsoft** [comment]
I just logged the same issue as #1137 without realizing it was a dup. But I would give this bug a higher priority, because we have blog posts directing users to run some of these tests, and running pytest within the test folder (as described above) is a pain, and makes debugging into these tests harder. I propose a different solution in #1137.
