### ISSUE TITLE
[Issue]: Azure Openai DALL.E 3 Can't it be used in Autogen Studio workflow?

### ISSUE THREAD

**Issue by Cloudinfo-Github** [microsoft/autogen#1149]
### Describe the issue

The module settings used in the workflow have been set up, but an error that requires OpenAI's API key still occurs.

### Screenshots and logs

![image](https://github.com/microsoft/autogen/assets/133182477/6af4e29a-f52a-45df-9af7-ec5f3de59fb2)

![image](https://github.com/microsoft/autogen/assets/133182477/c49051cf-bf8a-4753-b5a4-b7fcf64526b0)

**Comment by rickyloynd-microsoft** [comment]
@victordibia

**Comment by victordibia** [comment]
@Cloudinfo-Github ,

It appears you are trying to use the generate images skill . It requires and OPENAI_API_KEY to be available in the environment where autogen executes code. 

How are you currently setting your   OPENAI_API_KEY environment variable ?

**Comment by Cloudinfo-Github** [comment]
@victordibia ,

My dall-e-3 environment variables are written like this
![image](https://github.com/microsoft/autogen/assets/133182477/b8fe1642-dd8f-47ce-92e0-5ddcc1bd0d67)

**Comment by Cloudinfo-Github** [comment]
@victordibia ,
Thanks for your reply,I would like to confirm whether the api key in the skill is written directly in the code of the skill?

**Comment by victordibia** [comment]
You can 

- write it in the code of the skill (not recommended in general to have keys in code)
- Or read it from an environment variable. If you go this route, you must ensure that the environment variable is correctly set otherwise, the code will not run.  A potential pointer on setting env variables in [windows ](https://stackoverflow.com/questions/55500857/how-can-i-set-the-environment-variables-in-windows)-

**Comment by Cloudinfo-Github** [comment]
@victordibia,

OK, I got it, thanks A lot
