### ISSUE TITLE
[Bug]: Autogen Studio UI 2.0, all new Skills are saved as skill.py

### ISSUE THREAD

**Issue by mercuryyy** [microsoft/autogen#1248]
### Describe the bug

all new skills added is saved as skill.py and not as function_name.py

<img width="1258" alt="Screenshot 2024-01-14 at 9 24 55 AM" src="https://github.com/microsoft/autogen/assets/7463132/02156148-0121-4820-b8f6-525d9a93064d">

**Comment by victordibia** [comment]
Thanks for noting this.  
I will update this interface to include a better skill description field. 
In general, it does not matter the exact skill name used, all skills are integrated into the prompt as part of the llm call.

**Comment by huangpan2507** [comment]
> Thanks for noting this. I will update this interface to include a better skill description field. In general, it does not matter the exact skill file name (skill.py etc) used, all skills are integrated into the prompt that the Agent uses.

Hi，@victordibia: 
I have a doubt about "prompt that the Agent uses", do you mean the "System Message" under Agents, 
I click primary_assistant under Agents，the default message is 
`"You` are a helpful assistant that can use available functions when needed to solve problems. At each point, do your best to determine if the user's request has been addressed. IF THE REQUEST HAS NOT BEEN ADDRESSED, RESPOND WITH CODE TO ADDRESS IT. IF A FAILURE OCCURRED (e.g., due to a missing library) AND SOME ADDITIONAL CODE WAS WRITTEN (e.g. code to install the library), ENSURE THAT THE ORIGINAL CODE TO ADDRESS THE TASK STILL GETS EXECUTED. If the request HAS been addressed, respond with a summary of the result. The summary must be written as a coherent helpful response to the user request e.g. 'Sure, here is result to your request ' or 'The tallest mountain in Africa is ..' etc. The summary MUST end with the word TERMINATE. If the  user request is pleasantry or greeting, you should respond with a pleasantry or greeting and TERMINATE." `

And I had created some skill under Skills, then I add this new skill I created under Agents Specification primary_assistant /Skills.
**The question is**: if I want autogen use these new skills (eg, the new skill is about play video), what kind of message should I type in the chat? should I change the System Message under Agent Specification primary_assistant? like, add  "Please use the skill that you had " ?
Looking forward to your response, thanks!

**Comment by victordibia** [comment]
Hi @huangpan2507 ,

The [workflow manager ](https://github.com/microsoft/autogen/blob/autogenstudio/samples/apps/autogen-studio/autogenstudio/workflowmanager.py)automatically adds the skills to your agent [prompt](https://github.com/microsoft/autogen/blob/b1201b6d99b1db602c1fab1b68cf67278fd159ca/samples/apps/autogen-studio/autogenstudio/utils/utils.py#L236), in addition to the system message.



![Image](https://github.com/microsoft/autogen/assets/1547007/1a2e18e2-03bf-4e31-b4fc-578ad4f77833) 

![Image](https://github.com/microsoft/autogen/assets/1547007/f85078af-9702-499c-8243-3ff166478711)
