### ISSUE TITLE
[Bug]: GET request for files using wrong path in autogenstudio

### ISSUE THREAD

**Issue by tjb4578** [microsoft/autogen#1296]
### Describe the bug

After executing the sine wave example, the sine_wave.png file does not display.  I then tried my own custom example and the same thing happened.  The terminal shows that the GET request for the file ended in a 404.

```
INFO:     127.0.0.1:53348 - "GET /api/files/user/user/198fb9b77fb10d10bae092eea5789295/sine_wave.png HTTP/1.1" 404 Not Found
```

Here is the actual path to the file:

```
\files\user\198fb9b77fb10d10bae092eea5789295\sine_wave.png
```

I'm not sure where the second `user` is coming from in the GET request.  It looks like it might be a concatenation issue.  I'm running this on Windows 11 with Mistral Instruct 7B running on LM Studio.  I tweaked the default system message slightly to remove the TERMINATE command, as this was causing autogen to terminate before the task was completed successfully.  Not sure if that would have any bearing on this though.

### Expected Behavior

The GET request should use the correct URI and return a 200.

### Screenshots and logs

![Screenshot 2024-01-16 222236](https://github.com/microsoft/autogen/assets/5381852/0df09128-5990-407c-8423-cf4e951c86f3)

### Additional Information

Autogen version: 0.0.27a0
Operating System: Windows 11
Python Version: 3.10.6

**Comment by a-w-b** [comment]
Same on Windows 10 with standard installation using anaconda, no change of the default setup, just tried the same use case with exactly the same result as reported by tjb4578.

**Comment by victordibia** [comment]
Hi,

I believe this is a windows issue where some code that works correctly on linux resolves incorrectly on windows.
This [function](https://github.com/microsoft/autogen/blob/23d6e1ec8a99027e22d976f3db455b66d68612d4/samples/apps/autogen-studio/autogenstudio/utils/utils.py#L136) is what determines the url of files that have been updated. There is change it resolves incorrectly on windows. I'll take a look

**Comment by Starskimmer** [comment]
(Hopefully someone finds this useful) I managed to patch this by simply making a soft symbolic link loop to correct the behaver. (didn't feel like compiling a fix from source so a no-code solution is as follows)
launch an administration CMD
mklink /D "YOURPYTHONFOLDER(E.G. Anaconda\envs\YOUR ENVIROMENT e.g. (ag)\Lib\site-packages\autogenstudio\web\files\user\user\" "YOURPYTHONFOLDER(E.G. Anaconda\envs\YOUR ENVIROMENT e.g. (ag)\Lib\site-packages\autogenstudio\web\files\user" 
this creates a simple loop where the  /user/user folder points to the /user/ folder. ^_^

Incidentally I would recommend solving the OS path issues by implementing the 'pathlib' library. for example Windows uses "\" instead of "/" which can be a major issue on cross platform use but pathlib just deals with that.

from what i can see the point of failure in the function is line 184 :: uid = dest_dir.split("/")[-1]
just replace with 
                dest_dir_as_path = pathlib.Path(dest_dir)
                uid = dest_dir_as_path.parent.name
and remember to import the library at the top
import pathlib

**Comment by victordibia** [comment]
@Starskimmer ,

Thanks for the note. I think you are right. 
Adding a [fix](https://github.com/microsoft/autogen/commit/91eba071cd681b259e7a3ddc37595f969f4e5882) .
Will get my paws on a windows machine at some point and test this out.

**Comment by victordibia** [comment]
This has been addressed and tested to work on windows.
Closing out for now. Feel free to reopen if still seeing a related issue.
