### ISSUE TITLE
[Feature Request]: allow silent=True while initiating a group chat

### ISSUE THREAD

**Issue by ari9dam** [microsoft/autogen#1335]
### Is your feature request related to a problem? Please describe.

group_chat always print to console, there is no way to prevent the print

### Describe the solution you'd like

allow silent=True in initiate_chat()

**Comment by ekzhu** [comment]
I think the solution is quite simple: add a silent argument to the `GroupChatManager` class. I think the only place that prints out to the console is in:
https://github.com/microsoft/autogen/blob/main/autogen/agentchat/groupchat.py#L388
and
https://github.com/microsoft/autogen/blob/main/autogen/agentchat/groupchat.py#L437

**Comment by cliff-4** [comment]
@ekzhu Can you please specify how exactly one should add the silent argument?

I tried adding a `silent=True` parameter when initiating the `GroupChatManager` class, but I got a TypeError that silent is not a valid input for a `ConversableAgent` (since the parameter is passed on to this class). Thanks for your help!

**Comment by ekzhu** [comment]
I think in this case `silent` should be `GroupChatManager`'s own argument, as `ConversableAgent` doesn't have this argument.

**Comment by sonichi** [comment]
`silent` is a parameter of `send`

**Comment by jtoy** [comment]
I have a PR, but its not working properly. I gave GroupChatManager a silent option and I pass it to send, but the messages are never silenced. Can I get some feedback on this:
https://github.com/microsoft/autogen/pull/2212 @sonichi @ekzhu
