### ISSUE TITLE
[Feature Request]:   Autogen Studio unable to change human input mode

### ISSUE THREAD

**Issue by steve52003** [microsoft/autogen#1358]
### Describe the bug

When I spin up autogen studio and try to create a new agent, I can't change the human input mode from NEVER to anything else.  There is no other selection.  This is with all agents including user proxy agents.

**Comment by korla-plankton** [comment]
I am also seeing this

Steps to reproduce
Standard installation on linux in virtualenv, accessing studio with either firefox or chrome, create a new agent

Expected Behavior
Able to select 'ALWAYS', 'NEVER' and 'TERMINATE'

Screenshots and logs

![Screenshot from 2024-01-22 13-53-16](https://github.com/microsoft/autogen/assets/11466487/c76eda48-16af-40ab-8154-86db03c8a028)

Additional Information

Only 'NEVER' is shown in the drop-down list

**Comment by gagb** [comment]
This feature is on the roadmap already: https://github.com/microsoft/autogen/issues/737
Requires extra work; contributions are welcome.

**Comment by Jsin01** [comment]
+1 for this feature

**Comment by kuhnster01** [comment]
+1

**Comment by sid-newby** [comment]
+1

**Comment by plc1220** [comment]
+1

**Comment by owly** [comment]
+1

**Comment by JingPush** [comment]
+1

**Comment by Schalex01** [comment]
+1
