### ISSUE TITLE
Getting "Running Scripts is Disabled on this System" on windows with use_docker set to False

### ISSUE THREAD

**Issue by mrauter1** [microsoft/autogen#166]
Hello,

Apparently running scripts in powershell is disabled by default on Windows, so when the UserProxyAgent tries to execute a shell script this error occur.

Code to reproduce:
`from autogen import AssistantAgent, UserProxyAgent, config_list_from_json`
`config_list = config_list_from_json(env_or_file="OAI_CONFIG_LIST")`
`assistant = AssistantAgent("assistant", llm_config={"config_list": config_list})`
`user_proxy = UserProxyAgent("user_proxy", code_execution_config={"work_dir": "coding", "use_docker": False})`
`user_proxy.initiate_chat(assistant, message="Plot a chart of NVDA and TESLA stock price change YTD.")`

The error will happen when the agent attempts a shell execution.

**Comment by qingyun-wu** [comment]
Do you still have this error if you use autogen with version number >= 0.1.8?

**Comment by mrauter1** [comment]
Yes.
On 0.1.8 shell execution works on windows with Docker. Without Docker it will only work by changing Powershell’s default security configurations. 

One solution is to use CMD instead of Powershell. I can make a pull request.

**Comment by sonichi** [comment]
Thanks. What about adding an argument "shell" with default to powershell on windows? The added security from powershell can protect beginners.

**Comment by mrauter1** [comment]
I think using Powershell as default for beginners is more risky, they would have to enable script execution for Powershell which is not straightforward and can introduce vulnerabilities. Using CMD does not require any system changes. 

The shell argument would be overkill at this stage of the project IMO, since it is Windows specific and the benefit is not clear. 

It would be cool if someone using autogen with windows and code execution can chime in.

**Comment by sonichi** [comment]
Thanks for sharing the thoughts. @afourney what would you recommend?

**Comment by AllanSchergerGitHub** [comment]
> I think using Powershell as default for beginners is more risky, they would have to enable script execution for Powershell which is not straightforward and can introduce vulnerabilities. Using CMD does not require any system changes.
> 
> The shell argument would be overkill at this stage of the project IMO, since it is Windows specific and the benefit is not clear.
> 
> It would be cool if someone using autogen with windows and code execution can chime in.

Here is the context of the error messages I get on windows 10 (sharing it to help others) related to the powershell permissions issue when running the 'agentchat_auto_feedback_from_code_execution.ipynb' demo. This error message sequence will show up repeatedly as it attempts to solve the same problem over and over again.

A couple thoughts:
1) the agent(s) need to be able to recognize that there is a repeating pattern to the error and either:
a) attempt other solutions or 
b) break out of the loop and provide update to the human and/or seek human intervention.
2) If it can break out of the loop and interact with a human I would be fine with either the manual powershell option or the cmd line terminal option at this stage given the desire mentioned earlier to avoid scope creep.


===========================================================
user_proxy (to assistant):

exitcode: 1 (execution failed)
Code output: 
Traceback (most recent call last):
  File ".\", line 3, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'


--------------------------------------------------------------------------------
assistant (to user_proxy):

I apologize for the confusion. It seems that the 'yfinance' module is not installed in your Python environment. 

You can install it using pip, which is a package manager for Python. Here is the command to install yfinance:

```sh
# shell script
pip install yfinance
```


/* other details of the message intentionally not included here to avoid being too verbose */


user_proxy (to assistant):

exitcode: 1 (execution failed)
Code output: 
.\ : File 
 cannot be loaded because 
running scripts is disabled on this system. For more information, see about_Execution_Policies at 
[https:/go.microsoft.com/fwlink/?LinkID=135170.](https://go.microsoft.com/fwlink/?LinkID=135170.)
At line:1 char:1
+ .\
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by sonichi** [comment]
@afourney or @pcdeadeasy do you have any recommendation? Could you read @mrauter1 's suggestion and advise? Feel free to discuss on Discord if that helps.

**Comment by halr9000** [comment]
Please don't revert to cmd, that would be going backwards in time to the year 2006. @klumsy have you tried autogen yet?

**Comment by jojje** [comment]
I'm having the exact same problem. First I thought the message was from OpenAI since I know they run on Azure nowadays, and because I've never installed nor used anything called powershell. But from this bug report is seems the error message is actually originating from the host on which autogen is running (a windows 10 machine).

Any advice on how to get it to just use cmd.exe, or exec the python interpreter directly, instead of going through this... powershell ?

**Comment by sonichi** [comment]
@ekzhu fyi

**Comment by ekzhu** [comment]
@jojje you may want to check out the `ipython-embedded` executor in the next release. See my reply to a different thread: https://github.com/microsoft/autogen/discussions/261#discussioncomment-8431447

If you have a prototype or a notebook please share in #agent-coding channel on our Discord sever. PR welcome!

**Comment by sonichi** [comment]
v0.2.13 has been released.
