### ISSUE TITLE
[Issue]: Group Chat Manager Is Not working Properly.

### ISSUE THREAD

**Issue by MihirDavada** [microsoft/autogen#1660]
### Describe the issue

When user_proxy agent Ask Question to hr_assistant , It hr_assistant asks three question to the user and once hr_assistant get output of three question , it should call leave_bot() function which is executed by the executor_assistant. above code works fine while using  one to one chat(user_proxy to hr_assistant) , but it does not when i am using group chat. 

```
hr_prompt = "
  Role: HR.
  Responsibilities:
    - You Have Two Responsibility.

      1) Ask the user the following three questions.

            1) Type of Leave(Inquire whether the user needs Sick Leave or Casual Leave)
            2) Dates of Leave(Ask the user for the start and end dates of their leave)
            3) Reason for Leave:(Request the reason for taking the leave.)

      2) Please ensure the information is accurately recorded in the specified format. Once you got all the data , ask user for confirmation. If user confirmed ,Then call the leave related
         agent function( leave_bot()) and pass this obj.

            obj = {
                "types_of_leave": {Type of Leave},
                "start_date": {Start Date},
                "end_date": {End Date},
                "reason_for_leave": {Reason for Leave}
            }

      3)Important Notes:

        1) Do not call the leave_bot() tool , untill all the data is gathered.
        2) Once all the data is gathered , then call leave_bot() tool.
        3) Once The Task Is Done , Reply 'Terminate' Message.
        4) Only use the tools that you have been provided with.
"
executor_prompt = "
Role: Code Executor
Responsibilities : Your Task Is To Excute Code.
"

hr_assistant = autogen.AssistantAgent(
    name="hr",
    system_message=hr_prompt,
    llm_config=llm_config,
)

executor_proxy = autogen.UserProxyAgent(
    name="executor",
    human_input_mode="NEVER",
    system_message=executor_prompt,
    code_execution_config={
        "work_dir": ".",
        "use_docker": False,
    },
)

user_proxy = autogen.UserProxyAgent(
    name="user_proxy",
    system_message="A Human Admin.Interact with the manager.",
    is_termination_msg=lambda x: x.get("content", "") and x.get(
        "content", "").rstrip().endswith("TERMINATE"),
    human_input_mode="ALWAYS",
    code_execution_config=False
)

groupchat = autogen.GroupChat(
    agents=[user_proxy, hr_assistant, executor_proxy], messages=[], max_round=50)
manager = autogen.GroupChatManager(
    groupchat=groupchat, llm_config=llm_config, )


@executor_proxy.register_for_execution()
@hr_assistant.register_for_llm(name="leave_bot", description="HR for Leave Management")
def leave_bot(leave_obj: Annotated[object, "object"]):
    return leave_obj


hr_assistant.reset()
user_proxy.reset()
manager.reset()


user_proxy.initiate_chat(
    manager, message="I Want To Take Leave."
)

user_proxy.initiate_chat(
    hr_assistant, message="I Want To Take Leave."
)

user_proxy.initiate_chat(
    manager, message="I Want To Take Leave."
)
```

### Screenshots and logs

![image](https://github.com/microsoft/autogen/assets/101976200/1e9db044-fce4-40af-82aa-b325e7ed09e0)

**Comment by MihirDavada** [comment]
Previously It Works Fine With Old Version , But After Updating New Version GroupChatManager Is Not Working Properly.
![image](https://github.com/microsoft/autogen/assets/101976200/c7dd2df4-d665-4e6e-92eb-55f004a7705c)
![image](https://github.com/microsoft/autogen/assets/101976200/3c48bdcd-ee41-4d29-92b0-02a0e55efded)

**Comment by ekzhu** [comment]
Remove user proxy from the group chat.

This looks like a perfect case for one-on-one chat, is there a reason for making this into a group chat?

**Comment by MihirDavada** [comment]
Yes Because I Have another agents like travel agents , image_agent , excel agents.  I have to make it group_chat.

**Comment by ekzhu** [comment]
Interesting scenario! if you have a working prototype, you are welcome to share it on our example page or gallery page, and on our discord.

**Comment by MihirDavada** [comment]
can you tell me why GroupChatManager Is Not Working Properly. I Mentioned In the prompt that do not call leave_bot() function before collecting data from the user but it automatically filled the data without taking user input and called the function.

**Comment by ekzhu** [comment]
It works for me. What model are you using? I am using GPT-4. This is using the exact same code you posted earlier. I have user proxy inside the group chat too. 

<details>
<summary>Details</summary>

The return type of the function 'leave_bot' is not annotated. Although annotating it is optional, the function should return either a string, a subclass of 'pydantic.BaseModel'.
user_proxy (to chat_manager):

I Want To Take Leave.

--------------------------------------------------------------------------------
hr (to chat_manager):

Sure, I would need some details from you.

1) What type of leave are you applying for? (Sick Leave or Casual Leave)
2) Could you please let me know the start and end dates for your leave?
3) Could you also provide the reason for this leave?

--------------------------------------------------------------------------------
Provide feedback to chat_manager. Press enter to skip and use auto-reply, or type 'exit' to end the conversation: sick leave, 11/1/2024 to 11/12/2024, illness
user_proxy (to chat_manager):

sick leave, 11/1/2024 to 11/12/2024, illness

--------------------------------------------------------------------------------
hr (to chat_manager):

Got it. Here are the details you've provided:

1) Type of Leave: Sick Leave
2) Dates of Leave: From 11/1/2024 to 11/12/2024
3) Reason for Leave: Illness

Could you please confirm if all the details are correct?

--------------------------------------------------------------------------------
Provide feedback to chat_manager. Press enter to skip and use auto-reply, or type 'exit' to end the conversation: yes
user_proxy (to chat_manager):

yes

--------------------------------------------------------------------------------
hr (to chat_manager):

***** Suggested tool Call (call_q9ui7kCtS9z0KIakzHi6SumS): leave_bot *****
Arguments: 
{
  "leave_obj": {
    "types_of_leave": "Sick Leave",
    "start_date": "11/1/2024",
    "end_date": "11/12/2024",
    "reason_for_leave": "Illness"
  }
}
**************************************************************************

--------------------------------------------------------------------------------

>>>>>>>> EXECUTING FUNCTION leave_bot...
executor (to chat_manager):

executor (to chat_manager):

***** Response from calling tool "call_q9ui7kCtS9z0KIakzHi6SumS" *****
{"types_of_leave": "Sick Leave", "start_date": "11/1/2024", "end_date": "11/12/2024", "reason_for_leave": "Illness"}
**********************************************************************

--------------------------------------------------------------------------------

hr (to chat_manager):

I have successfully recorded your sick leave request from 11/1/2024 to 11/12/2024 due to illness. This information has been passed on for further processing. Terminate.

--------------------------------------------------------------------------------

eProvide feedback to chat_manager. Press enter to skip and use auto-reply, or type 'exit' to end the conversation: 
>>>>>>>> NO HUMAN INPUT RECEIVED.

>>>>>>>> USING AUTO REPLY...


user_proxy (to chat_manager):



--------------------------------------------------------------------------------
Provide feedback to chat_manager. Press enter to skip and use auto-reply, or type 'exit' to end the conversation: 
>>>>>>>> NO HUMAN INPUT RECEIVED.

>>>>>>>> USING AUTO REPLY...
user_proxy (to chat_manager):



--------------------------------------------------------------------------------
hr (to chat_manager):



--------------------------------------------------------------------------------
Provide feedback to chat_manager. Press enter to skip and use auto-reply, or type 'exit' to end the conversation: exit

</details>

To make it more robust I would set the `description` field in each agent. So the group chat manager is not using the system message of each agent to decide speaker.

**Comment by MihirDavada** [comment]
Can You Provide Me Code..?

**Comment by MihirDavada** [comment]
Thanks. It Works With `description`. Thank You For Solving Problem.
