### ISSUE TITLE
I expected agent to write something like "I need more knowledge".

### ISSUE THREAD

**Issue by thinkall** [microsoft/autogen#167]
I no longer have error "maximum recursion depth exceeded while calling a Python object", but now agent returns two answers (both of them are ok, but why two? is this a normal behaviour?). Example answer looks like below. In the meantime, agent get more snippets, which is ok, but I expected agent to write something like "I need more knowledge".

--------------------------------------------------------------------------------
assistant (to ragproxyagent):

Dear Toan,
We can definitely provide you with a 38T Chainring GTRO gearbox. As for the ERider 73mm torque sensing bottom bracket compatibility, we have a solution for 73mm shells as well. When making a purchase, please specify "BB73mm" in the comment. As for the prices, you will have to check our website for the current prices as they may vary. Please, let me know if you have any other questions.
--------------------------------------------------------------------------------

_Originally posted by @wiiiktor in https://github.com/microsoft/autogen/issues/155#issuecomment-1752549820_

**Comment by thinkall** [comment]
https://github.com/microsoft/autogen/pull/155#issuecomment-1752550398

**Comment by wiiiktor** [comment]
Seems like this problem is solved, at least outpu is different. My configuration was:

ragproxyagent = RetrieveUserProxyAgent(
    name="ragproxyagent",
    human_input_mode="NEVER",
    max_consecutive_auto_reply=1,  # tu CHYBA wpisujemy, ile razy ragproxyagent ma sie dopominac o wiecej wiedzy
    retrieve_config={
        "task": "qa",
        "docs_path": corpus_file,
        "chunk_token_size": 2000,
        "model": config_list[2]["model"],  # tutaj wybieramy model
        "client": chromadb.PersistentClient(path="/tmp/chromadb"),
        # "collection_name": "2wikimultihopqa",
        "chunk_mode": "one_line",
        "embedding_model": "all-MiniLM-L6-v2",
        "customized_prompt": PROMPT_MULTIHOP,
        "customized_answer_prefix": "the answer is",
    },
) 

and I added: 

        "get_or_create": True,
        "update_context": False,

and you can see the current output below. By the way, how can I configure it to only see the final answer?: 
----------------------
assistant (to ragproxyagent):

Dear Toan, we offer the 38T Chainring GTRO at a certain price (please refer to our online store for the latest pricing). Regarding the ERider 73mm torque sensing bottom bracket, it should be compatible with our GTRO, but please note that we do not sell bottom brackets separately as they are part of the bike. However, as noted in a previous enquiry, I can confirm we have a 73mm version of the Sempu T2.3 sensor. For the detailed price, once again I recommend checking our website or contacting our customer service for the most accurate and up-to-date information.

--------------------------------------------------------------------------------
ragproxyagent (to assistant):



--------------------------------------------------------------------------------
assistant (to ragproxyagent):

Dear Toan, we offer the 38T Chainring GTRO at a certain price (please refer to our online store for the latest pricing). Regarding the ERider 73mm torque sensing bottom bracket, it should be compatible with our GTRO, but please note that we do not sell bottom brackets separately as they are part of the bike. However, as noted in a previous enquiry, I can confirm we have a 73mm version of the Sempu T2.3 sensor. For the detailed price, once again I recommend checking our website or contacting our customer service for the most accurate and up-to-date information.

--------------------------------------------------------------------------------

Process finished with exit code 0

**Comment by thinkall** [comment]
I guess `By the way, how can I configure it to only see the final answer?` is not implemented yet.

**Comment by thinkall** [comment]
You can capture the printed message and extract the last message.

**Comment by wiiiktor** [comment]
Sure, I know it. With LLM! ;-)

**Comment by sonichi** [comment]
or you can set `silent` to True and print `assistant.last_message()`

**Comment by thinkall** [comment]
> or you can set `silent` to True and print `assistant.last_message()`

@wiiiktor have you tried this? It worked for me.

**Comment by wiiiktor** [comment]
print(assistant.last_message()['content']) works ok, 
but I do not know where to put this "silent": True parameter; 
I tried both in RetrieveUserProxyAgent and RetrieveAssistantAgent
(when I put this argument into RetrieveAssistantAgent, I have a message that I exceeded some token quota; putting into RetrieveUserProxyAgent has no effect at all) 

openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.
When I remove "silent": True parameter, it goes back to normal :)

**Comment by thinkall** [comment]
> print(assistant.last_message()['content']) works ok, but I do not know where to put this "silent": True parameter; I tried both in RetrieveUserProxyAgent and RetrieveAssistantAgent (when I put this argument into RetrieveAssistantAgent, I have a message that I exceeded some token quota; putting into RetrieveUserProxyAgent has no effect at all)
> 
> openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details. When I remove "silent": True parameter, it goes back to normal :)

It's a parameter of `initiate_chat`. Set it like `ragproxyagent.initiate_chat(assistant, problem=code_problem, silent=True) `

**Comment by wiiiktor** [comment]
yes, it worked. my complete output is now: 

/Users/wiiiktor/.........xxx......./notebook/rag-maile.py 
['Hello, We manufacturer USA made Ebikes, and have a few models that already use Schlumpf High Speed Drive.  We are curious about the Efneo 3 speed, and the potential compatibility with our bike and maybe even a torque sensing BB.  We currently use BSA standard English thread BB 83mm internal width. Can your drive be made compatible with our bikes? We also have other bikes with 68mm and 73mm bottom brackets also BSA standard.  Chris']
['Dear Chris, we offer 68mm / 73mm / 80mm BSA bottom brackets without torque sensing and 68mm German THUN torque sensing BB (it adds a lot to the price, though); Franek, can you please send commercial details to Chris? and here some technical files for THUN X-Cell RT 3.0: http://efneo.com/filesss/manuals/THUN_X-CELL_RT_3_0_Datasheet_2019.pdf http://efneo.com/filesss/manuals/Technical%20file%20Thun.pdf']


>>>>>>>>>>>>  Below are outputs of Case 1  <<<<<<<<<<<<


Trying to create collection.
Collection autogen-docs already exists.
doc_ids:  [['doc_2', 'doc_4', 'doc_16', 'doc_64', 'doc_15']]
Adding doc_id doc_2 to context.
Adding doc_id doc_4 to context.
Adding doc_id doc_16 to context.
Adding doc_id doc_64 to context.
Adding doc_id doc_15 to context.
Updating context and resetting conversation.
doc_ids:  [['doc_10', 'doc_52', 'doc_51', 'doc_9', 'doc_68']]
Adding doc_id doc_10 to context.
Adding doc_id doc_52 to context.
Adding doc_id doc_51 to context.
Adding doc_id doc_9 to context.
Adding doc_id doc_68 to context.
-----------------
Dear Chris, 

Yes, our Efneo 3 speed gearbox is compatible with BSA standard English thread BBs of 68mm, 73mm and also 83mm internal width. However, just be sure that the BB Shell is clean from colliding elements like the rear chainstay. In terms of compatibility with a torque sensing BB, unfortunately, our gearbox does not have a built-in one. But if you have the torque sensing system installed in another place in your bike, it should work just fine. We're looking forward to potentially partnering with you! Feel free to reach out if you have any other concerns or questions.

Process finished with exit code 0
