### ISSUE TITLE
[Bug]: docker library should not be required if `use_docker` is False

### ISSUE THREAD

**Issue by PyroGenesis** [microsoft/autogen#1741]
### Describe the bug

All of my executor agents have `use_docker` set to False. However, code execution still tries to import the `docker` library and attempts to check if it is running, throwing a `ModuleNotFoundError`.

### Steps to reproduce

1. Install `autogen`, but do not install `docker`
2. Setup up a `UserProxyAgent` with its `use_docker` property in `code_execution_config` set to False
3. Use an `AssistantAgent` (or another `UserProxyAgent`) to write code and execute with the agent defined in step 2

### Expected Behavior

Code should execute locally successfully

### Additional Information

AutoGen: v0.2.14
OS: Windows 10
Python: 3.10.11

I've put the code I changed to make it work into #1740.

**Comment by gagb** [comment]
@olgavrou @afourney

**Comment by afourney** [comment]
ModuleNotFoundError is because the Docker python library is not installed. You can safely install the python Docker module even if you don't plan to use Docker -- in fact I think it is now a requirement.

If it were trying to use Docker, you would see an error relating to the connection, not a module error.

**Comment by PyroGenesis** [comment]
You're right, something was wrong with my dependency resolver because of which the docker library was not installed: https://github.com/microsoft/autogen/pull/1740#issuecomment-1957432353
