### ISSUE TITLE
Autogen llm_config error

### ISSUE THREAD

**Issue by doganaktarr** [microsoft/autogen#1863]
Hi, when my version is `pyautogen==0.2.16` Autogen gives this error:

```terminal
ValueError: Please either set llm_config to False, or specify a non-empty 'model' either in 'llm_config' or in each config of 'config_list'.
``` 

But when i switch to the `pyautogen==0.2.2` version. It does not gives any error.

This is my llm_config:
```py
{'config_list': 
        [{
        'base_url': 'http://0.0.0.0:8053',
        'api_key': 'NULL'
    }],
    'cache_seed': 25}
```

And litellm runs on that port without any issues.

**Comment by qingyun-wu** [comment]
There are some updates in the required format of config_list. Could you set llm_config to False, or specify a non-empty 'model' either in 'llm_config' or in each config of 'config_list' as suggested in the error message if you are using 0.2.16? Thank you!

**Comment by jackgerrits** [comment]
If I am interpreting this correctly it seems that litellm does not need a model arg to work? So perhaps requiring this is too heavy handed?

**Comment by sonichi** [comment]
@jackgerrits good point. I'm OK with removing the check in ConversableAgent. @gunnarku what do you think?

**Comment by ekzhu** [comment]
Looping in @olgavrou

**Comment by gunnarku** [comment]
The dilemma is between breaking the backward compatibility and more robust validation for preconditions (and I admit that I am biased towards more formality ;-)).

If we remove the checking for the presence of the `model` attribute, we'll regress to the state described in https://github.com/microsoft/autogen/issues/1522 (the root cause for https://github.com/microsoft/autogen/pull/1654).

If it's the only known case of overly aggressive validation, then modifying the configuration by the user is an obvious fix.

Issuing a warning message is a middle-ground solution.

However, @[@jackgerrits](https://github.com/jackgerrits)  and @[sonichi](https://github.com/sonichi), this is your show - do what's right for AutoGen customers ;-)

**Comment by sonichi** [comment]
I tried to find a solution to accommodate both requirements in #1946

**Comment by olgavrou** [comment]
> Looping in @olgavrou

custom models also don't necessarily need the `model` to be set
