### ISSUE TITLE
[Bug]:  role in chat_history is confusing and it is proabably reversed

### ISSUE THREAD

**Issue by amzker** [microsoft/autogen#1878]
### Describe the bug

![image](https://github.com/microsoft/autogen/assets/35922655/c30e000f-2023-4db1-8936-b4bfc894b58a)

This message is from user rather from assistant
Now there can be two things 
1. Either I don't know what role means
my understanding is that role means who is saying or speaking, not to whom it is replying. here it is reversed i guess
2. there is bug

### Steps to reproduce

1. create any agent
2. have chat and store it into variable 

```python
variable = user.initiate_chat(agent, message=f"{context}\n{task_to_do}")
```
3. get the output and see

```
variable.chat_history[-1] # or simply check manually
```

### Expected Behavior

role should have been user , not assistant

**Comment by rickyloynd-microsoft** [comment]
This is a common source of confusion. When two agents are conversing, each maintains its own copy of the message history, and their roles are reversed in those two copies. The reason for this is because openai defined a fixed set of message roles like user and assistant, and autogen follows those roles in its message lists. In a group chat it may be that none of the agents represent the user, and yet every message list sent to the LLM must be annotated with user and assistant roles. The simple rule to remember is that every agent carries the assistant role in its own copy of the message list.
