### ISSUE TITLE
[Bug]: Changing previously saved agent model deletes agent

### ISSUE THREAD

**Issue by JonMike12341234** [microsoft/autogen#1999]
### Describe the bug

Changing previously saved agent model deletes agent

### Steps to reproduce

Wrote up a few agents, which now doesn't have the description column bug! ;)
Ran the workflow sucessfully in the playground.
Navigated back to agents and changed agents settings from the previous local Mistral to a newly installed local Zephyr and the agents disapeared upon clicking ok/save.

**Comment by victordibia** [comment]
Hi @JonMike12341234 ,

Thanks for sharing the bug.
Can you create and attach a short recording of the bug you are seeing and steps to reproduce? 
E..g
- Create agent 
- Select agent, change a field
- Click Ok 
- Agent is deleted (instead of updates showing up)

Also, kindly add the version of AGS you have. Current version is v0.0.53. Please use `pip install -U autogenstudio` to upgrade to lates.

**Comment by rysweet** [comment]
closing stale - op never replied.
