### ISSUE TITLE
MacOS?

### ISSUE THREAD

**Issue by pangia** [microsoft/autogen#206]
Having some issues getting this running correctly with Docker on MacOS. Is running on MacOS a possibility?

**Comment by sonichi** [comment]
I don't have a mac. I've asked on Discord.

**Comment by gagb** [comment]
What  issues are you getting? I am able to run AutoGen with Docker on my Mac.

**Comment by shouldnotappearcalm** [comment]
code can run natively, set `'use_docker': False`，use like this
```python
assistant = AssistantAgent(
    name="assistant",
    llm_config=llm_config,
    code_execution_config={
        'use_docker': False
    }
)
```

**Comment by gagb** [comment]
I think the OG question is about using Docker correctly...

**Comment by jgroehm** [comment]
Just switched over to mac from windows - had a similar issue, will share what worked on my M3 in case others find it helpful. 
Ref: https://stackoverflow.com/questions/44084846/cannot-connect-to-the-docker-daemon-on-macos

from terminal:
find ~/Library/Containers/com.docker.docker -name "*docker.raw.sock"

temporary solution (make sure to use path found above):
export DOCKER_HOST=unix:///Users/$USER/Library/Containers/com.docker.docker/Data/docker.raw.sock

Assuming temporary works as expected:
Symlink  (requires password):
sudo ln -s /Users/$USER/Library/Containers/com.docker.docker/Data/docker.raw.sock /var/run/docker.sock

**Comment by sonichi** [comment]
Thanks for sharing that. @jackgerrits @gagb @zwd-ms is this worth adding to doc website?

**Comment by jackgerrits** [comment]
I am super glad that a resolution was found!

Based on the stack overflow link and Docker's release notes it only affects Docker 4.13, and was reverted due to the confusion caused in 4.14. (https://docs.docker.com/desktop/release-notes/#4140) Could be worth adding to FAQ but I don't think we should add it as noise to the main docker docs due to the limited scope of the issue

**Comment by jgroehm** [comment]
Agree with leaving it off the main docs, will mention a couple more things that may be relevant:
1. The default builder on my machine was set to desktop-linux (rather than default docker)
2. Docker version is 25.0.3
3. The symlink piece wasn't as robust as I thought, but adding the export DOCKER_HOST piece to the .venv activate script did the trick 
4. using rye for package management
5. I only have about a week's experience with a MacBook so giant grain of salt for anything beyond works on my machine

**Comment by jackgerrits** [comment]
Thanks so much for the extra context - hopefully that helps anyone with the issue who finds this thread
