### ISSUE TITLE
ValueError: AzureOpenAIChatCompletionClient requires explicit model capabilities

### ISSUE THREAD

**Issue by tyler-suard-parker** [microsoft/autogen#3887]
### What happened?

I am trying to use AzureOpenAIChatCompletionClient with agents.  I have specified my environment variables.  What does this mean?  What is a model capability?

### What did you expect to happen?

I expected it to run without an error

### How can we reproduce it (as minimally and precisely as possible)?

from autogen_core.components.models import AzureOpenAIChatCompletionClient
agent = BaseChatAgent(
        "writer_agent",
        model_client=AzureOpenAIChatCompletionClient(model="gpt-4"),
        description="An expert at writing",
        system_message=f"""You are an employee.""")

### AutoGen version

autogen-agentchat==0.4.0dev1

### Which package was this bug in

Core

### Model used

gpt-4

### Python version

3.11

### Operating system

Windows

**Comment by jackgerrits** [comment]
Here's how to do it: https://microsoft.github.io/autogen/dev/user-guide/core-user-guide/cookbook/azure-openai-with-aad-auth.html

It's necessary since the model deployment in azure isn't necessarily the name of the model we don't know what the pointed to model is capable of. So we ask you to specify what it can do. We'd prefer a better solution here to be honest but we settled on this for now

We have a TODO to document this: https://github.com/microsoft/autogen/issues/3630

**Comment by tyler-suard-parker** [comment]
@jackgerrits That makes sense, thank you.
