### ISSUE TITLE
.NET o1 model support

### ISSUE THREAD

**Issue by rysweet** [microsoft/autogen#3926]
### What feature would you like to be added?

need to support o1 models

### Why is this needed?

to enable usage of o1 inside agents

**Comment by LittleLittleCloud** [comment]
Does o1 model needs special setup, other than no system message, no temperature/stop token/max token?

**Comment by LittleLittleCloud** [comment]
There's an example in autogen.net v0.2 on how to use o1 models
- https://github.com/microsoft/autogen/blob/main/dotnet/samples/AutoGen.OpenAI.Sample/Connect_To_OpenAI_o1_preview.cs

For autogen v0.4, since it doesn't associated to any specific model client, my imagination would be the consumpition of o1 model will fall into the specific model client, like M.E.A.I, SK or autogen.net v0.2?
