### ISSUE TITLE
Unable to change GroupChat confiuration after instantiating a GroupChatManager

### ISSUE THREAD

**Issue by afourney** [microsoft/autogen#409]
There are situations where one may want to change the maximum number of rounds in a GroupChat, or add or remove parties in the chat, without re-instantiating everything and losing message history (e.g., it could be a setting in a UI, etc.)

However, the GroupChat object is passed to the GroupChatManager as a configuration that gets registered in the Manager's register_reply function. This creates a clone, disassociated from the original GroupChat object.

https://github.com/microsoft/autogen/blob/80954e4b8d0752fd4772f339dee419fbf1debc6f/autogen/agentchat/conversable_agent.py#L179C33-L179C33

I've been able to work around this, but it's extremely hacky:

```
# Hack to change the max_round configuration
for item in manager._reply_func_list:
    if isinstance(item["config"], GroupChat):
        item["config"].max_round = 10
        break
```

Ideally, there would be a cleaner way to access this critical configuration object post-instantiation.

**Comment by sonichi** [comment]
Since it's a groupchat-specific thing, we can change this line:
https://github.com/microsoft/autogen/blob/3cb39304c39b7b6c6068e0df91e2f5e1992d6d19/autogen/agentchat/groupchat.py#L147
into
`self.groupchat=...`
To make `max_round` dynamically changeable, we'll also need to modify the for loop following it.
