### ISSUE TITLE
For autogen-ext sub modules, make sure classes can be imported independently without getting import errors from missing dependencies in other modules

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#4408]
Right now the directory structure is not great for submodule import:

```
autogen_ext
- code_executors
  __init__.py
  _azure_container_code_executor.py
  _docker_code_executor.py
- agents
  __init__.py # The init file contains all the imports from sub modules, causing import errors
```

It should be:

```
autogen_ext
- code_executors
  - __init__.py
  - azure
    - __init__.py
    _azure_container_code_executor.py
  - docker
    - __init__.py 
    - _docker_code_executor.py
- agents
  - __init__.py 
  - web_surfer
    - __init__.py
    - _multi_modal_web_surfer.py
```

**Comment by lspinheiro** [comment]
@ekzhu , I think the pattern that @jackgerrits  adopted for code executors and tools was to move the imports inside the classes and throw a runtime error if the dependencies are missing. I did something similar in #4423. The main difference is that I still kept the imports in the top of the module but sued a module variable to track whether the dependencies are available and delay the exception to runtime. The only drawback is having some imports done twice because pyright complains the varaibles may be unbound (even with the variable check in the code).

 If that pattern is acceptable then I can update the models and web surfer in the same way.


BTW, happy thanksgiving!
