### ISSUE TITLE
Team to support a list of messages as input to a task

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#4472]
Currently a team only support a single message for task.

```python
result = await team.run(task="...")
```

It should support a list of messages, to prepopulate the context of the agents.

```python
result = await team.run(task=[TextMessage(...), TextMessage(...)])
```

This allows passing a previous conversation history from another team. 

This is also useful for nested chats to prepopulate the team participants with messages before generating a response.

**Comment by victordibia** [comment]
Interesting idea .. 
This sounds like what `team.load_state()` does in #4100. 
Also, in the above example 

```
result = await team.run(task=[TextMessage(...), TextMessage(...)])
```

Does this populate the context for ALL agents or some agents etc? 
In PR #4436 ,`team_state` has an `agent_states` field that is a dict and maps to each agent. This way specific list of messages are mapped to the actual agent from which they were serialized (or created for) in `team.load_state()`

**Comment by ekzhu** [comment]
I think the list of messages as task is to allow better integration with applications. E.g., in a scenario where users might type multiple messages before the application triggering the team run, and nest chats. 

The load and save states are designed for persistence and editing of agent states. 

They both serve different purposes.

**Comment by KanikaChoudhary1312** [comment]
Hi,

I have created a chat application using autogen latest version, in every session when we start asking question, every question run seperate without remembering the previous question or context, how to make sure that the conversation is been related
if a question is been asked it should know the context of the answer to start the conversation in flow.
What should I use memory or team state,
if we use memory, since the agents can do longer conversation, it runs out of token with the messages.

How do I deal? and If I use state - Can we use team_result from RUN table and use that as state for the sessions ?

**Comment by ekzhu** [comment]
@KanikaChoudhary1312 I would appreciate if you can use a GitHub discussion or Discord rather than commenting on closed issue -- just to make it easier to organize.

**Comment by KanikaChoudhary1312** [comment]
Apologies, I have created a new discussion to follow on : https://github.com/microsoft/autogen/discussions/6307

Have done the setup with team_config and run_stream works fine. 
Unfortunately for every run, GroupChat starts the conversation from scratch, also do not follow the previous context in a session. 
I tried passing List of Messages, but due to heavy Rag content it runs out of token. As a temporary solution passing last 20 messages, but would like to know if I missing the better solution to handle this either using state or memory plugin.

Thanks in advance, we can follow the conversation on QA ticket.
