### ISSUE TITLE
Adoption of Agent Protocol

### ISSUE THREAD

**Issue by hackgoofer** [microsoft/autogen#49]
https://github.com/AI-Engineer-Foundation/agent-protocol, and join our discord: https://discord.gg/cXKrtegQrZ

Curious if you'd consider using the Agent Protocol we have developed. This OSS project resides under a non-profit called "AI Engineer Foundation". The mission is to establish industry standards so that people do not have to re-invent the wheels, so that we can collaborate more.

By implementing Agent Protocol, you'd be able to communicate with all other Agents out there that also conform to the same protocol as well as being able to be benchmarked.

AutoGPT is running a [hackathon](https://lablab.ai/event/autogpt-arena-hacks) and they have created a benchmarking tool that is built with AgentProtocol. Other projects that have adopted us other than AutoGPT is: GPTEngineer, PolyAGI, Beebot, E2B... the list is growing.

Excited to hear back from you!

**Comment by sonichi** [comment]
@pcdeadeasy @victordibia @qingyun-wu @gagb @JieyuZ2 sth. to consider in the roadmap.

**Comment by sonichi** [comment]
There is a team using autogen for the AutoGPT hackathon. It'll be helpful to follow up with them to hear their suggestion in this issue.

**Comment by janaka** [comment]
@hackgoofer thanks for pointing me at this thread. 

I'm new to AutoGen and Agent Protocol. Been following a little on paper. For past several months been building OSS RAG app/stack ( https://github.com/docqai/docq ). Just about to start experimenting with agents using AutoGen. As a general principle, I lean on adopting established standards regardless of them being intentional or not.

With my current understanding of AutoGen and Agent Protocol, given AutoGen hasn't yet adopted  Agent Protocol, it seems like I can for now adopt`/ap/v1/agent/tasks` in our app for now. But not `/ap/v1/agent/tasks/{task_id}/steps` because it's AutoGen already has an interface to handle agent <> agent coms and orchestration. Do I have the correct mental model?

**Comment by ph-ausseil** [comment]
What is the status since Autogen has released Autogen Studio ?

**Comment by sonichi** [comment]
@rajan-chari @kinnym could you check about this question? I think it your interests.
cc @victordibia @ekzhu

**Comment by janaka** [comment]
update: since my last comment ^ I've spent a lot more time experimenting with AutoGen (both Py and Dotnet implementation) and thinking about how to implement agent-based system for real use cases.

I still don't see the concept of steps playing a part with AutoGen type agents systems.
