### ISSUE TITLE
TeachableAgent video

### ISSUE THREAD

**Issue by rickyloynd-microsoft** [microsoft/autogen#532]

**Comment by sonichi** [comment]
Quick comment: issues like this don't need to be created all as independent issues and added to the roadmap project. We can have one meta issue and add it to the roadmap, and create subtasks using the tasklist for the meta issue. The subtasks don't get added to the roadmap project.

**Comment by oneCodeScholar** [comment]
Is there a video available? The link doesn't seem to work. Thanks!

**Comment by rickyloynd-microsoft** [comment]
> Is there a video available? The link doesn't seem to work. Thanks!

There is no video yet. What link is broken?

**Comment by oneCodeScholar** [comment]
Oh okay, thanks for the update! I mistakenly click on a button thinking it would launch a video but it didn't. I'm looking forward to the video! I have autogen running locally really well, with two LLMs, as I've spend the past few weeks getting it to work. I'd like to really know more about autogen. What are some of the best sources, just the manuals, github and youtube? I saw there are other ways of chatting with the agents, instead of just a group broadcast, and I'd like to experiment with that more.  Thanks!

**Comment by rickyloynd-microsoft** [comment]
@oneCodeScholar, it's exciting that you've got multiple local LLMs running! The sources you listed (manuals, github and youtube) are very helpful. Also the blogs and our discord channel, where many are discussing ways to use group chats.

I'm still curious, where is this "button" that looked like it might launch a video?

**Comment by oneCodeScholar** [comment]
Okay cool, I haven't seen the discord for autogen. Do you have a link? The button I saw was just the green Open button (lol). Could you look at my autogen code? I know its not the greatest but with your expertise it could be. Thanks!

**Comment by rickyloynd-microsoft** [comment]
[AutoGen discord](https://discord.gg/pAbnFJrkgZ)

**Comment by oneCodeScholar** [comment]
Awesome thanks!

**Comment by rickyloynd-microsoft** [comment]
> Quick comment: issues like this don't need to be created all as independent issues and added to the roadmap project. We can have one meta issue and add it to the roadmap, and create subtasks using the tasklist for the meta issue. The subtasks don't get added to the roadmap project.

Done.

**Comment by rickyloynd-microsoft** [comment]
TeachableAgent is now covered by our extended AutoGen video in preparation for NeurIPS.
