### ISSUE TITLE
Parallel function calling in autogen

### ISSUE THREAD

**Issue by skzhang1** [microsoft/autogen#589]
OpenAI now supports parallel function calls when openai >= 1.1.0. 

> Parallel function call is helpful for cases where you want to call multiple functions in one turn. For example, you may want to call functions to get the weather in 3 different locations at the same time. In this case, the model will call multiple functions in a single response.

To make autogen support this feature, it needs to update the dependency for OpenAI to the latest version. Currently, autogen can also call multiple function calls but in a sequence pattern. 
For autogen users, anyone know what kind of use-cases could benefit from this parallel function call feature and demonstrate it worth an improvement compared with sequence calling?

**Comment by NicholasZolton** [comment]
I believe the primary use case for this feature is saving tokens. By doing parallel functions instead of sequential function calls, you avoid repeatedly sending both the function structure and previous chat history, both of which take up a significant amount of tokens. I don't believe this significantly affects the performance or accuracy of the function calls, but it's entirely possible that there's some benefit to doing it in parallel.

**Comment by afourney** [comment]
The dependency was updated in #588, which is now merged.

**Comment by JacobJohn17756677** [comment]
hey can you tell me how to do parallel processing in autogen ??

**Comment by rysweet** [comment]
believe this is now supported.
