### ISSUE TITLE
Cloud Vector DB for TeachableAgent

### ISSUE THREAD

**Issue by Abhishek-Balram** [microsoft/autogen#864]
It would be really useful if the TeachableAgent use a cloud vector db for storing and retrieving memos instead of having the vector db stored locally on my machine. 

Something similar to the QdrantRetrieveUserProxyAgent (e.g. a QdrantTeachableAgent) would be really good since Qdrant is a cloud-native vector db. Even better would be a teachable agent where any vector db client (including cloud-native ones) can be passed in the teach_config

@Anush008 @AyushExel

**Comment by rickyloynd-microsoft** [comment]
This would be a reasonable extension. Users can currently plug in other DBs by writing a class that inherits from TeachableAgent then modifying that class. Meanwhile, it would be great if somebody volunteers to enhance TeachableAgent so that users can plug in any vector DB without writing code. I don't have time myself, since I'm concentrating on making teachable agents fundamentally more capable, independent of any particular DB.

**Comment by AyushExel** [comment]
@rickyloynd-microsoft I can work on it next week

**Comment by benjamin-mogensen** [comment]
Is there any example code of how to initialise and load the Chrome DB separate from the RAG agent? I would like to do this as part of a start up of the app, of when someone actively wants / needs to refresh the Chrome DB. Apologies if it is trivial, I am new to autogen :)

**Comment by rickyloynd-microsoft** [comment]
> Is there any example code of how to initialise and load the Chrome DB separate from the RAG agent? I would like to do this as part of a start up of the app, of when someone actively wants / needs to refresh the Chrome DB. Apologies if it is trivial, I am new to autogen :)

Yes, please see autogen/agentchat/contrib/teachable_agent.py

**Comment by ottkehe** [comment]
Hi @AyushExel, do you have any news about this feature? It would be awesome!

**Comment by DevOtts** [comment]
Hi @AyushExel, do you have any news about this feature? It would be awesome!

**Comment by rickyloynd-microsoft** [comment]
Stale. No longer planned.
