### ISSUE TITLE
[Feature Request]: Enhance GraphGroupChat with "Conditional edges"

### ISSUE THREAD

**Issue by yiranwu0** [microsoft/autogen#959]
### Is your feature request related to a problem? Please describe.

@joshkyh  
When building a workflow with Graph GroupChat, users might what to specify a conditional check before the chat is moving to the next stage.
 In this case, it would be great to  allow user to add a “conditional edge” to graph, that is to determine when certain agents come into action.

In the figure below, the condition to move on to next stage is to check if the code execution has any errors.
![conditioned_edge](https://github.com/microsoft/autogen/assets/32823396/2b51f924-6b78-44d5-bf6f-2d7bae185a83)

**Comment by afourney** [comment]
@kevin666aa @joshkyh I haven't looked into this super closely yet, so forgive my silly question, but the product manager appears twice in the graph. I would expect two outgoing edges from product manager (one to the Architect, and one to the Engineer). Isn't this also conditional? 

TBH, this figure looks more like a state machine than a communications graph. That's ok... but it's a fundamentally a different beast, no?

**Comment by kevin666aa** [comment]
> @kevin666aa @joshkyh I haven't looked into this super closely yet, so forgive my silly question, but the product manager appears twice in the graph. I would expect two outgoing edges from product manager (one to the Architect, and one to the Engineer). Isn't this also conditional?
> 
> The same applies to the Executor.
> 
> TBH, this figure looks more like a state machine than a communications graph. That's ok... but it's a fundamentally a different beast, no?

Yes, product manager and executor does appear twice. The idea is that the manager will first process a request and them construct tasks based, and using the graph for a hierarchical flow.

I was thinking of flow that these agents are bypassed one by one, and trying to fit that scenario into the graph groupchat. But as you said, it should be a state machine instead of communications graph in this sense.

In the graph groupchat, "two outgoing edges" from product manager means that product manager can talk to both Architect and Engineer,
But if drawing "two outgoing edges" in the figure above, it would mean that the Product Manager will talk to Architect and Engineer at the same time.
Thanks for the thoughts and I will think it over!

**Comment by yiranwu0** [comment]
We now allow custom speaker selection and construct StateFlow with groupchat.

**Comment by Deykeepcomn4me** [comment]
This is hacker please contact fbi
